---
# tasks file for sbaerlocher.ovirt-guest-agent

- name: add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/defaults.yml"

- name: install Ovirt Guest Agent
  package: name={{ item }} state=latest
  with_items:
    - "{{ ovirt_package }}"
  notify: enabled Ovirt Guest Agent

- name: restart Ovirt Guest Agent
  service: name={{ ovirt_guest_agent_service_name }} state=restarted