---
# tasks file for sbaerlocher.ovirt-guest-agent

- name: add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/defaults.yml"

- block:
  - apt_repository: repo='deb http://download.opensuse.org/repositories/home:/evilissimo:/deb/Debian_7.0/ ./' state=present
  - apt_key: id=73A1A299 url=http://download.opensuse.org/repositories/home:/evilissimo:/deb/Debian_7.0/Release.key state=present
  when: ansible_distribution == "Debian"

- name: install Ovirt Guest Agent
  package: name={{ item }} state=latest
  with_items:
    - "{{ ovirt_package }}"
  notify:
    - enabled Ovirt Guest Agent
    - restart Ovirt Guest Agent